

import React from 'react';
import { ArrowDown as ArrowDownIcon, Facebook as FacebookIcon, Instagram as InstagramIcon, Linkedin as LinkedinIcon, Mail as MailIcon, Sparkles as SparklesIcon } from 'lucide-react';
import { motion } from 'framer-motion';
import { Reveal } from '../components/ui/Reveal';
import { DIRECTORS, EXECUTIVE_COMMITTEE, LEADERSHIP_VALUES, type LeadershipMember } from '../lib/leadershipData';

const accentClass: Record<string, string> = { crimson: 'from-crimson-600/80 to-rose-400/30', gold: 'from-gold/80 to-amber-300/30', rose: 'from-rose-600/80 to-pink-300/30', amber: 'from-amber-600/80 to-yellow-300/30', violet: 'from-violet-700/80 to-purple-300/30', sky: 'from-sky-700/80 to-cyan-300/30', orange: 'from-orange-700/80 to-amber-300/30', fuchsia: 'from-fuchsia-700/80 to-pink-300/30', cyan: 'from-cyan-700/80 to-sky-300/30' };

function Socials({ member }: {member: LeadershipMember;}) {
  return <div className="flex items-center gap-2"><a href="https://www.linkedin.com/" aria-label={`${member.name} on LinkedIn`} className="rounded-full bg-white/15 p-2 text-white backdrop-blur transition hover:bg-gold hover:text-ink"><LinkedinIcon className="h-3.5 w-3.5" /></a><a href="https://www.facebook.com/" aria-label={`${member.name} on Facebook`} className="rounded-full bg-white/15 p-2 text-white backdrop-blur transition hover:bg-gold hover:text-ink"><FacebookIcon className="h-3.5 w-3.5" /></a><a href="https://www.instagram.com/" aria-label={`${member.name} on Instagram`} className="rounded-full bg-white/15 p-2 text-white backdrop-blur transition hover:bg-gold hover:text-ink"><InstagramIcon className="h-3.5 w-3.5" /></a></div>;
}

function MemberCard({ member, featured = false }: {member: LeadershipMember;featured?: boolean;}) {
  return <article className={`group relative overflow-hidden rounded-5xl bg-ink shadow-soft transition duration-500 hover:-translate-y-2 ${featured ? 'min-h-[560px]' : 'min-h-[420px]'}`}><img loading="lazy" src={member.image} alt={member.name} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/50 to-transparent" /><div className={`absolute inset-0 opacity-0 transition duration-500 group-hover:opacity-80 bg-gradient-to-br ${accentClass[member.accent]}`} /><div className="absolute inset-x-6 bottom-6 text-white"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-gold">{member.avenue ? `${member.role} · ${member.avenue}` : member.role}</p><h3 className={`mt-2 font-display font-bold ${featured ? 'text-4xl' : 'text-2xl'}`}>{member.name}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/70">“{member.quote}”</p><p className="mt-3 text-sm leading-6 text-white/55">{member.bio}</p><div className="mt-5 flex items-center justify-between"><Socials member={member} /><a href={`mailto:hello@rotaractucsc.org?subject=Message%20for%20${encodeURIComponent(member.name)}`} aria-label={`Email ${member.name}`} className="flex items-center gap-2 rounded-full border border-white/20 px-3 py-2 text-xs font-bold transition hover:border-gold hover:text-gold"><MailIcon className="h-3.5 w-3.5" /> Contact</a></div></div></article>;
}

export function BoardPage() {
  return <main className="overflow-hidden bg-cream pt-24 text-ink dark:bg-ink dark:text-white">
    <section className="relative isolate min-h-[680px] overflow-hidden px-6 pb-20 pt-28 md:pb-28 md:pt-40"><img src="/42cc44eb-6af7-43f4-b8f5-17bc1fdadf2a.jpg" alt="Rotaract leaders connecting on campus" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-ink via-ink/80 to-ink/20" /><motion.div aria-hidden animate={{ y: [0, -14, 0], rotate: [0, 7, 0] }} transition={{ duration: 7, repeat: Infinity }} className="absolute right-[13%] top-36 hidden h-20 w-20 rounded-[2rem] border border-white/30 bg-white/10 backdrop-blur-md md:block" /><motion.div aria-hidden animate={{ y: [0, 20, 0] }} transition={{ duration: 8, repeat: Infinity }} className="absolute bottom-28 right-[28%] hidden h-12 w-12 rounded-full bg-gold md:block" /><div className="mx-auto flex max-w-6xl flex-col justify-end"><Reveal className="max-w-3xl"><div className="flex w-fit items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-gold backdrop-blur-md"><SparklesIcon className="h-3.5 w-3.5" /> 2025 / 26 Board</div><h1 className="mt-6 font-display text-5xl font-extrabold leading-[.98] tracking-tight text-white md:text-8xl">Meet Our<br /><span className="text-gold">Leadership.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">A group of curious, grounded young leaders shaping the club’s next chapter with care, courage and a lot of collective energy.</p></Reveal><a href="#leadership" className="mt-14 flex w-fit items-center gap-3 text-sm font-semibold text-white/80 transition hover:text-gold"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-white/30 bg-white/10"><ArrowDownIcon className="h-4 w-4" /></span> Meet the people</a></div></section>

    <section id="leadership" className="scroll-mt-28 px-6 pb-24 pt-8 md:pb-32"><div className="mx-auto max-w-6xl"><Reveal className="mb-14 max-w-2xl"><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-crimson-500 dark:text-gold">Executive committee</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight md:text-6xl">A board built for brave ideas.</h2><p className="mt-5 leading-8 text-ink/60 dark:text-white/60">Eleven distinct perspectives, aligned around one belief: young people can build the kind of change they want to see.</p></Reveal><div className="grid gap-5 md:grid-cols-12">{EXECUTIVE_COMMITTEE.map((member, index) => <Reveal key={member.name} delay={index * .04} className={index === 0 ? 'md:col-span-7 md:row-span-2' : index === 1 ? 'md:col-span-5' : index === 2 || index === 3 ? 'md:col-span-4' : 'md:col-span-3'}><MemberCard member={member} featured={index === 0} /></Reveal>)}</div></div></section>

    <section className="bg-ink px-6 py-24 text-white md:py-32"><div className="mx-auto max-w-6xl"><Reveal className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-gold">Directors</p><h2 className="mt-4 font-display text-4xl font-bold md:text-6xl">Purpose needs its specialists.</h2></div><p className="max-w-sm text-sm leading-7 text-white/60">Each director stewards an avenue of service, turning shared intentions into work people can feel.</p></Reveal><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{DIRECTORS.map((member, index) => <Reveal key={`${member.name}-${member.avenue}`} delay={index * .045}><MemberCard member={member} /></Reveal>)}</div></div></section>

    <section className="bg-white px-6 py-24 dark:bg-white/5 md:py-32"><div className="mx-auto max-w-6xl"><Reveal className="mb-14 max-w-2xl"><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-crimson-500 dark:text-gold">What guides us</p><h2 className="mt-4 font-display text-4xl font-bold md:text-5xl">Values that stay when the room gets quiet.</h2></Reveal><div className="grid gap-4 md:grid-cols-3">{LEADERSHIP_VALUES.map(({ title, text, icon: Icon }, index) => <Reveal key={title} delay={index * .05}><div className="group min-h-52 rounded-4xl border border-ink/5 bg-cream p-7 transition duration-500 hover:-translate-y-1 hover:border-crimson-500/30 hover:shadow-soft dark:border-white/10 dark:bg-ink"><Icon className="h-7 w-7 text-crimson-500 transition-transform duration-300 group-hover:scale-110 dark:text-gold" /><h3 className="mt-8 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-ink/60 dark:text-white/60">{text}</p></div></Reveal>)}</div></div></section>

  </main>;
}