

import React from 'react';
import { ArrowRight as ArrowRightIcon, CalendarDays as CalendarDaysIcon, Clock3 as Clock3Icon, Facebook as FacebookIcon, Globe2 as Globe2Icon, Instagram as InstagramIcon, Linkedin as LinkedinIcon, Mail as MailIcon, MapPin as MapPinIcon, Phone as PhoneIcon, Youtube as YoutubeIcon } from 'lucide-react';
import { motion } from 'framer-motion';
import { ContactForm } from '../components/contact/ContactForm';
import { FaqList } from '../components/contact/FaqList';
import { Blob } from '../components/ui/Decor';
import { Reveal } from '../components/ui/Reveal';

const details = [{ title: 'Club address', text: 'UCSC, 35 Reid Ave, Colombo 00700', icon: MapPinIcon }, { title: 'Email us', text: 'hello@rotaractucsc.org', icon: MailIcon }, { title: 'Call us', text: '+94 11 234 5678', icon: PhoneIcon }, { title: 'Meetings', text: 'Every Thursday · 5:30 PM', icon: CalendarDaysIcon }, { title: 'Venue', text: 'UCSC Student Activity Centre', icon: Clock3Icon }];
const socials = [{ title: 'Instagram', handle: '@rotaractucsc', icon: InstagramIcon, href: 'https://www.instagram.com/' }, { title: 'Facebook', handle: 'Rotaract UCSC', icon: FacebookIcon, href: 'https://www.facebook.com/' }, { title: 'LinkedIn', handle: 'Rotaract UCSC', icon: LinkedinIcon, href: 'https://www.linkedin.com/' }, { title: 'YouTube', handle: 'Rotaract Stories', icon: YoutubeIcon, href: 'https://www.youtube.com/' }];

export function ContactPage() {
  return <main className="overflow-hidden bg-cream text-ink dark:bg-ink dark:text-white">
    <section className="relative isolate min-h-[640px] overflow-hidden px-6 pb-20 pt-28 md:pt-40"><img src="/10727d3a-30fb-43e1-8b11-25608a02c3e1.jpg" alt="Rotaractors welcoming visitors on campus" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-ink via-ink/80 to-ink/20" /><motion.div aria-hidden animate={{ y: [0, -18, 0], rotate: [0, 8, 0] }} transition={{ duration: 8, repeat: Infinity }} className="absolute right-[14%] top-32 hidden h-24 w-24 rounded-[2rem] border border-white/30 bg-white/10 backdrop-blur-md md:block" /><motion.div aria-hidden animate={{ x: [0, 14, 0], y: [0, 12, 0] }} transition={{ duration: 7, repeat: Infinity }} className="absolute bottom-32 right-[28%] hidden h-11 w-11 rounded-full bg-gold md:block" /><div className="mx-auto flex max-w-6xl flex-col justify-end"><Reveal className="max-w-3xl"><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-gold">The door is open</p><h1 className="mt-5 font-display text-6xl font-extrabold leading-none text-white md:text-8xl">Let’s <span className="text-gold">Connect.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">Whether you want to collaborate, volunteer for a project or just learn a little more, we would love to hear from you.</p></Reveal></div></section>

    <section className="relative mx-auto -mt-10 max-w-6xl px-6"><div className="grid gap-4 rounded-5xl border border-white/50 bg-white/85 p-4 shadow-soft backdrop-blur-xl dark:border-white/10 dark:bg-ink/85 md:grid-cols-5">{details.map(({ title, text, icon: Icon }, index) => <Reveal key={title} delay={index * .05}><div className="rounded-4xl p-5 transition hover:bg-navy-500/5 dark:hover:bg-white/5"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-navy-500/10 text-navy-500 dark:bg-gold/15 dark:text-gold"><Icon className="h-5 w-5" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-ink/45 dark:text-white/45">{title}</p><p className="mt-2 text-sm font-semibold leading-6">{text}</p></div></Reveal>)}</div></section>

    <section className="relative px-6 py-24 md:py-32"><Blob className="-left-20 top-16 h-80 w-80 bg-gold/25" /><div className="relative mx-auto grid max-w-6xl gap-12 md:grid-cols-[.9fr_1.1fr] md:items-start"><Reveal><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-navy-500 dark:text-gold">Start a conversation</p><h2 className="mt-4 font-display text-4xl font-bold leading-tight md:text-5xl">Good things often start with a hello.</h2><p className="mt-6 max-w-md leading-8 text-ink/60 dark:text-white/60">Tell us what brings you here. Whether it is a project idea, a volunteering question or a partnership opportunity, the right person will follow up.</p><div className="mt-10 rounded-4xl bg-ink p-6 text-white"><Globe2Icon className="h-6 w-6 text-gold" /><p className="mt-5 font-display text-xl font-bold">Need directions?</p><p className="mt-2 text-sm leading-6 text-white/60">We meet at UCSC in the heart of Colombo. Plan your visit before you arrive.</p><div className="mt-5 flex flex-wrap gap-3"><a href="https://www.google.com/maps/search/?api=1&query=University+of+Colombo+School+of+Computing" className="rounded-full bg-gold px-4 py-2.5 text-sm font-bold text-ink">Get directions</a><a href="https://www.google.com/maps/search/?api=1&query=University+of+Colombo+School+of+Computing" className="rounded-full border border-white/20 px-4 py-2.5 text-sm font-bold transition hover:border-gold hover:text-gold">Open in Maps</a></div><div className="mt-6 overflow-hidden rounded-3xl border border-white/10"><iframe title="University of Colombo School of Computing map" src="https://www.google.com/maps?q=University%20of%20Colombo%20School%20of%20Computing&output=embed" className="h-48 w-full grayscale contrast-125" loading="lazy" /></div></div></Reveal><Reveal delay={.1}><ContactForm /></Reveal></div></section>

    <section className="bg-ink px-6 py-24 text-white md:py-32"><div className="mx-auto max-w-6xl"><Reveal className="mb-12 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-gold">Find us where you are</p><h2 className="mt-4 font-display text-4xl font-bold md:text-5xl">The social side of service.</h2></div><p className="max-w-sm text-sm leading-7 text-white/60">Follow the in-between moments, project updates and the people behind the work.</p></Reveal><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{socials.map(({ title, handle, icon: Icon, href }, index) => <Reveal key={title} delay={index * .06}><a href={href} className="group block rounded-4xl border border-white/10 bg-white/5 p-6 transition duration-500 hover:-translate-y-2 hover:bg-white/10 hover:shadow-glow"><Icon className="h-8 w-8 text-gold transition-transform duration-300 group-hover:scale-110" /><h3 className="mt-10 font-display text-2xl font-bold">{title}</h3><p className="mt-2 text-sm text-white/55">{handle}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-gold">Follow along <ArrowRightIcon className="h-4 w-4" /></span></a></Reveal>)}</div></div></section>

    <section className="mx-auto max-w-5xl px-6 py-24 md:py-32"><Reveal className="mb-12 text-center"><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-navy-500 dark:text-gold">FAQ</p><h2 className="mt-4 font-display text-4xl font-bold md:text-5xl">A few helpful answers.</h2></Reveal><Reveal delay={.08}><FaqList /></Reveal></section>

    <section className="relative overflow-hidden bg-navy-500 px-6 py-24 text-white md:py-28"><div aria-hidden className="absolute -right-24 -top-20 h-96 w-96 rounded-full border-[48px] border-gold/20" /><div className="relative mx-auto flex max-w-6xl flex-col justify-between gap-8 md:flex-row md:items-end"><Reveal className="max-w-2xl"><p className="font-grotesk text-sm font-bold uppercase tracking-[.2em] text-gold">Collaboration starts here</p><h2 className="mt-4 font-display text-4xl font-bold leading-tight md:text-6xl">Let’s make an<br />impact together.</h2><p className="mt-5 leading-7 text-white/75">We welcome thoughtful partnerships, project collaborations and conversations that move communities forward.</p></Reveal><Reveal delay={.1}><a href="mailto:hello@rotaractucsc.org?subject=Partnership%20opportunity" className="inline-flex items-center gap-2 rounded-full bg-gold px-6 py-4 font-bold text-ink transition hover:-translate-y-1 hover:bg-white">Partner with us <ArrowRightIcon className="h-4 w-4" /></a></Reveal></div></section>
  </main>;
}